domain: fredfoss.github.io
url: https://fredfoss.github.io
# baseurl: /REPOSITORY-NAME/ # place folder name if the site is served in a subfolder
# theme: jekyll-theme-minima
# title: Fredrik's homepage
description: Welcome!
